"""empty message

Revision ID: 2e6d84dfd34a
Revises: 5d9f2ca7b98b
Create Date: 2020-05-30 09:27:33.345088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6d84dfd34a'
down_revision = '5d9f2ca7b98b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('matchType', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'matchType')
    # ### end Alembic commands ###
