"""empty message

Revision ID: 5a57ee0d7001
Revises: 2e6d84dfd34a
Create Date: 2020-05-30 23:40:08.318165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a57ee0d7001'
down_revision = '2e6d84dfd34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_ranked_season_stats',
    sa.Column('season_id', sa.String(length=256), nullable=False),
    sa.Column('player_id', sa.String(length=256), nullable=False),
    sa.Column('game_mode', sa.String(length=256), nullable=False),
    sa.Column('currentRankPoint', sa.Integer(), nullable=False),
    sa.Column('bestRankPoint', sa.Integer(), nullable=False),
    sa.Column('currentTier_Tier', sa.String(length=256), nullable=False),
    sa.Column('currentTier_subTier', sa.String(length=256), nullable=False),
    sa.Column('bestTier_Tier', sa.String(length=256), nullable=False),
    sa.Column('bestTier_subTier', sa.String(length=256), nullable=False),
    sa.Column('roundsPlayed', sa.Integer(), nullable=False),
    sa.Column('avgRank', sa.Float(), nullable=False),
    sa.Column('avgSurvivalTime', sa.Integer(), nullable=False),
    sa.Column('top10Ratio', sa.Float(), nullable=False),
    sa.Column('winRatio', sa.Float(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('kda', sa.Float(), nullable=False),
    sa.Column('kdr', sa.Float(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('roundMostKills', sa.Integer(), nullable=False),
    sa.Column('longestKill', sa.Float(), nullable=False),
    sa.Column('headshotKills', sa.Integer(), nullable=False),
    sa.Column('headshotKillRatio', sa.Float(), nullable=False),
    sa.Column('damageDealt', sa.Float(), nullable=False),
    sa.Column('dBNOs', sa.Integer(), nullable=False),
    sa.Column('reviveRatio', sa.Float(), nullable=False),
    sa.Column('revives', sa.Integer(), nullable=False),
    sa.Column('heals', sa.Integer(), nullable=False),
    sa.Column('boosts', sa.Integer(), nullable=False),
    sa.Column('weaponsAcquired', sa.Integer(), nullable=False),
    sa.Column('teamKills', sa.Integer(), nullable=False),
    sa.Column('playTime', sa.Integer(), nullable=False),
    sa.Column('killStreak', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season_id', 'game_mode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_ranked_season_stats')
    # ### end Alembic commands ###
