"""empty message

Revision ID: 5d9f2ca7b98b
Revises: 
Create Date: 2020-05-29 07:21:58.024619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9f2ca7b98b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=256), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('gameMode', sa.String(length=256), nullable=False),
    sa.Column('mapName', sa.String(length=256), nullable=False),
    sa.Column('isCustomMatch', sa.Boolean(), nullable=False),
    sa.Column('seasonState', sa.String(length=256), nullable=False),
    sa.Column('shardId', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.String(length=256), nullable=False),
    sa.Column('player_name', sa.String(length=256), nullable=False),
    sa.Column('shard_id', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('seasons',
    sa.Column('season_id', sa.String(length=256), nullable=False),
    sa.Column('is_current_season', sa.Boolean(), nullable=False),
    sa.Column('is_off_season', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('system_information',
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('player_lifetime_stats',
    sa.Column('player_id', sa.String(length=256), nullable=False),
    sa.Column('game_mode', sa.String(length=256), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('boosts', sa.Integer(), nullable=False),
    sa.Column('dBNOs', sa.Integer(), nullable=False),
    sa.Column('dailyKills', sa.Integer(), nullable=False),
    sa.Column('damageDealt', sa.Float(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('dailyWins', sa.Integer(), nullable=False),
    sa.Column('headshotKills', sa.Integer(), nullable=False),
    sa.Column('heals', sa.Integer(), nullable=False),
    sa.Column('killPoints', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('longestKill', sa.Float(), nullable=False),
    sa.Column('longestTimeSurvived', sa.Float(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('maxKillStreaks', sa.Integer(), nullable=False),
    sa.Column('mostSurvivalTime', sa.Float(), nullable=False),
    sa.Column('rankPoints', sa.Float(), nullable=False),
    sa.Column('revives', sa.Integer(), nullable=False),
    sa.Column('rideDistance', sa.Float(), nullable=False),
    sa.Column('roadKills', sa.Integer(), nullable=False),
    sa.Column('roundMostKills', sa.Integer(), nullable=False),
    sa.Column('roundsPlayed', sa.Integer(), nullable=False),
    sa.Column('suicides', sa.Integer(), nullable=False),
    sa.Column('swimDistance', sa.Float(), nullable=False),
    sa.Column('teamKills', sa.Integer(), nullable=False),
    sa.Column('timeSurvived', sa.Float(), nullable=False),
    sa.Column('top10s', sa.Integer(), nullable=False),
    sa.Column('vehicleDestroys', sa.Integer(), nullable=False),
    sa.Column('walkDistance', sa.Float(), nullable=False),
    sa.Column('weaponsAcquired', sa.Integer(), nullable=False),
    sa.Column('weeklyKills', sa.Integer(), nullable=False),
    sa.Column('weeklyWins', sa.Integer(), nullable=False),
    sa.Column('winPoints', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'game_mode')
    )
    op.create_table('player_match_stats',
    sa.Column('player_id', sa.String(length=256), nullable=False),
    sa.Column('match_id', sa.String(length=256), nullable=False),
    sa.Column('DBNOs', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('boosts', sa.Integer(), nullable=False),
    sa.Column('damageDealt', sa.Float(), nullable=False),
    sa.Column('deathType', sa.String(length=64), nullable=False),
    sa.Column('headshotKills', sa.Integer(), nullable=False),
    sa.Column('heals', sa.Integer(), nullable=False),
    sa.Column('killPlace', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('longestKill', sa.Float(), nullable=False),
    sa.Column('revives', sa.Integer(), nullable=False),
    sa.Column('rideDistance', sa.Float(), nullable=False),
    sa.Column('roadKills', sa.Integer(), nullable=False),
    sa.Column('swimDistance', sa.Float(), nullable=False),
    sa.Column('teamKills', sa.Integer(), nullable=False),
    sa.Column('timeSurvived', sa.Float(), nullable=False),
    sa.Column('vehicleDestroys', sa.Integer(), nullable=False),
    sa.Column('walkDistance', sa.Float(), nullable=False),
    sa.Column('weaponsAcquired', sa.Integer(), nullable=False),
    sa.Column('winPlace', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'match_id')
    )
    op.create_table('player_matches',
    sa.Column('player_id', sa.String(length=256), nullable=False),
    sa.Column('match_id', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'match_id')
    )
    op.create_table('player_season_stats',
    sa.Column('season_id', sa.String(length=256), nullable=False),
    sa.Column('player_id', sa.String(length=256), nullable=False),
    sa.Column('game_mode', sa.String(length=256), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('boosts', sa.Integer(), nullable=False),
    sa.Column('dBNOs', sa.Integer(), nullable=False),
    sa.Column('dailyKills', sa.Integer(), nullable=False),
    sa.Column('damageDealt', sa.Float(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('dailyWins', sa.Integer(), nullable=False),
    sa.Column('headshotKills', sa.Integer(), nullable=False),
    sa.Column('heals', sa.Integer(), nullable=False),
    sa.Column('killPoints', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('longestKill', sa.Float(), nullable=False),
    sa.Column('longestTimeSurvived', sa.Float(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('maxKillStreaks', sa.Integer(), nullable=False),
    sa.Column('mostSurvivalTime', sa.Integer(), nullable=False),
    sa.Column('rankPoints', sa.Integer(), nullable=False),
    sa.Column('revives', sa.Integer(), nullable=False),
    sa.Column('rideDistance', sa.Float(), nullable=False),
    sa.Column('roadKills', sa.Integer(), nullable=False),
    sa.Column('roundMostKills', sa.Integer(), nullable=False),
    sa.Column('roundsPlayed', sa.Integer(), nullable=False),
    sa.Column('suicides', sa.Integer(), nullable=False),
    sa.Column('swimDistance', sa.Float(), nullable=False),
    sa.Column('teamKills', sa.Integer(), nullable=False),
    sa.Column('timeSurvived', sa.Float(), nullable=False),
    sa.Column('top10s', sa.Integer(), nullable=False),
    sa.Column('vehicleDestroys', sa.Integer(), nullable=False),
    sa.Column('walkDistance', sa.Float(), nullable=False),
    sa.Column('weaponsAcquired', sa.Integer(), nullable=False),
    sa.Column('weeklyKills', sa.Integer(), nullable=False),
    sa.Column('weeklyWins', sa.Integer(), nullable=False),
    sa.Column('winPoints', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season_id', 'game_mode')
    )
    op.create_table('season_matches',
    sa.Column('season_id', sa.String(length=256), nullable=False),
    sa.Column('match_id', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('season_id', 'match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('season_matches')
    op.drop_table('player_season_stats')
    op.drop_table('player_matches')
    op.drop_table('player_match_stats')
    op.drop_table('player_lifetime_stats')
    op.drop_table('system_information')
    op.drop_table('seasons')
    op.drop_table('players')
    op.drop_table('matches')
    # ### end Alembic commands ###
